name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=.\coverage\lcov.info
    - name: Coveralls GitHub Action
      # You may pin to the exact commit or the version.
      # uses: coverallsapp/github-action@8cbef1dea373ebce56de0a14c68d6267baa10b44
      uses: coverallsapp/github-action@v1.1.2
      with:
        # 
        github-token: LIvsSvmbZREZjbor3dQucMjO5PpWl45Gf
        # Path to lcov file
        path-to-lcov: ../../coverage/lcov.info
