name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Coverage check
      uses: devmasx/coverage-check-action@v1.1.0
      with:
        # lcov | simplecov
        type: lcov # default is lcov
        # Github token for create checks
        token: World # default is World
        # Minimum coverage
        min_coverage: 50 # optional, default is 80
        # Json with coverage result
        result_path: .\coverage.json
